# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _hrl
else:
    import _hrl

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class FloatArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _hrl.FloatArray_swiginit(self, _hrl.new_FloatArray(nelements))
    __swig_destroy__ = _hrl.delete_FloatArray

    def __getitem__(self, index):
        return _hrl.FloatArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _hrl.FloatArray___setitem__(self, index, value)

    def cast(self):
        return _hrl.FloatArray_cast(self)

    @staticmethod
    def frompointer(t):
        return _hrl.FloatArray_frompointer(t)

# Register FloatArray in _hrl:
_hrl.FloatArray_swigregister(FloatArray)

HRL_SPRITE_SHADER = 0xFFFFFFFF
HRL_MESH_2D_SHADER = 0xFFFFFFFF - 1
HRL_MESH_3D_SHADER = 0xFFFFFFFF - 2
HRL_DEBUG_SHADER = 0xFFFFFFFF - 3
HRL_DEFAULT_POST_PROCESS_SHADER = 0xFFFFFFFF - 4

HRL_API_VERSION = _hrl.HRL_API_VERSION
HRL_T_ALBEDO = _hrl.HRL_T_ALBEDO
HRL_T_NORMAL = _hrl.HRL_T_NORMAL
HRL_T_SPECULAR = _hrl.HRL_T_SPECULAR
HRL_T_ROUGHNESS = _hrl.HRL_T_ROUGHNESS
HRL_T_METALIC = _hrl.HRL_T_METALIC
HRL_T_ALPHA = _hrl.HRL_T_ALPHA
HRL_T_EMISSIVE = _hrl.HRL_T_EMISSIVE
HRL_T_SHADOW_MAP = _hrl.HRL_T_SHADOW_MAP
HRL_T_CUBE_MAP = _hrl.HRL_T_CUBE_MAP
HRL_OPENGL_33 = _hrl.HRL_OPENGL_33
HRL_OPENGL_45 = _hrl.HRL_OPENGL_45
HRL_VULKAN = _hrl.HRL_VULKAN
HRL_D3D11 = _hrl.HRL_D3D11
HRL_D3D12 = _hrl.HRL_D3D12
HRL_METAL = _hrl.HRL_METAL
HRL_NVN = _hrl.HRL_NVN
HRL_GNM = _hrl.HRL_GNM
HRL_POINT_LIGHT = _hrl.HRL_POINT_LIGHT
HRL_DIRECTIONAL_LIGHT = _hrl.HRL_DIRECTIONAL_LIGHT
HRL_SPOT_LIGHT = _hrl.HRL_SPOT_LIGHT
HRL_SPRITE = _hrl.HRL_SPRITE
HRL_2D_MESH = _hrl.HRL_2D_MESH
HRL_3D_MESH = _hrl.HRL_3D_MESH
HRL_3D_SKELETAL_MESH = _hrl.HRL_3D_SKELETAL_MESH
HRL_DEBUG_HOLLOW = _hrl.HRL_DEBUG_HOLLOW
HRL_DEBUG_SOLID = _hrl.HRL_DEBUG_SOLID
HRL_ORTHO = _hrl.HRL_ORTHO
HRL_PERSPECTIVE = _hrl.HRL_PERSPECTIVE
HRL_FILTER_NEAREST = _hrl.HRL_FILTER_NEAREST
HRL_FILTER_LINEAR = _hrl.HRL_FILTER_LINEAR
HRL_FILTER_BILINEAR = _hrl.HRL_FILTER_BILINEAR
HRL_FILTER_TRILINEAR = _hrl.HRL_FILTER_TRILINEAR
HRL_FILTER_ANISOTROPIC = _hrl.HRL_FILTER_ANISOTROPIC
HRL_FILTER_SUPERSAMPLING = _hrl.HRL_FILTER_SUPERSAMPLING
HRL_DEBUG_VIEW_NONE = _hrl.HRL_DEBUG_VIEW_NONE
HRL_DEBUG_VIEW_UNLIT = _hrl.HRL_DEBUG_VIEW_UNLIT
HRL_DEBUG_VIEW_NORMAL = _hrl.HRL_DEBUG_VIEW_NORMAL
HRL_DEBUG_VIEW_LIGHTS = _hrl.HRL_DEBUG_VIEW_LIGHTS
HRL_NO_ERROR = _hrl.HRL_NO_ERROR
HRL_ERROR_INVALID_ID = _hrl.HRL_ERROR_INVALID_ID
HRL_INVALID_ENUM = _hrl.HRL_INVALID_ENUM
HRL_INVALID_VALUE = _hrl.HRL_INVALID_VALUE
HRL_INVALID_OPERATION = _hrl.HRL_INVALID_OPERATION
HRL_INVALID_BACKEND_OPERATION = _hrl.HRL_INVALID_BACKEND_OPERATION
HRL_SHADER_COMPILE_FAIL = _hrl.HRL_SHADER_COMPILE_FAIL
HRL_OUT_OF_MEMORY = _hrl.HRL_OUT_OF_MEMORY
HRL_INVALID_FILE_FORMAT = _hrl.HRL_INVALID_FILE_FORMAT
HRL_SEVERITY_WEAK_WARNING = _hrl.HRL_SEVERITY_WEAK_WARNING
HRL_SEVERITY_WARNING = _hrl.HRL_SEVERITY_WARNING
HRL_SEVERITY_ERROR = _hrl.HRL_SEVERITY_ERROR
HRL_SEVERITY_FATAL = _hrl.HRL_SEVERITY_FATAL
HRL_FOG_LINEAR = _hrl.HRL_FOG_LINEAR
HRL_FOG_EXPONENTIAL = _hrl.HRL_FOG_EXPONENTIAL
HRL_FOG_EXP_SQUARED = _hrl.HRL_FOG_EXP_SQUARED

def HRL_Init(_api):
    return _hrl.HRL_Init(_api)

def HRL_InitContext(_width, _height, _loader):
    return _hrl.HRL_InitContext(_width, _height, _loader)

def HRL_Shutdown():
    return _hrl.HRL_Shutdown()

def HRL_BeginFrame():
    return _hrl.HRL_BeginFrame()

def HRL_EndFrame():
    return _hrl.HRL_EndFrame()

def HRL_WindowResizeCallback(_width, _height):
    return _hrl.HRL_WindowResizeCallback(_width, _height)

def HRL_ErrorEnumToString(err):
    return _hrl.HRL_ErrorEnumToString(err)

def HRL_SeverityEnumToString(sev):
    return _hrl.HRL_SeverityEnumToString(sev)

def HRL_RegisterErrorCallback(_callback):
    return _hrl.HRL_RegisterErrorCallback(_callback)

def HRL_CreateMeshSprite(_sceneid):
    return _hrl.HRL_CreateMeshSprite(_sceneid)

def HRL_SetMeshPivotPoint(_meshid, x, y, z):
    return _hrl.HRL_SetMeshPivotPoint(_meshid, x, y, z)

def HRL_SetSpriteRegion(_meshid, min_u, min_v, max_u, max_v):
    return _hrl.HRL_SetSpriteRegion(_meshid, min_u, min_v, max_u, max_v)

def HRL_CreateMesh(_sceneid, _type, _vertices):
    return _hrl.HRL_CreateMesh(_sceneid, _type, _vertices)

def HRL_CreateMeshFromFile(_sceneid, _type, _data, _bufferSize):
    return _hrl.HRL_CreateMeshFromFile(_sceneid, _type, _data, _bufferSize)

def HRL_DeleteMesh(_meshid):
    return _hrl.HRL_DeleteMesh(_meshid)

def HRL_IsValidMesh(_id):
    return _hrl.HRL_IsValidMesh(_id)

def HRL_SetMeshMaterial(_meshid, _matid):
    return _hrl.HRL_SetMeshMaterial(_meshid, _matid)

def HRL_SetMeshLocation(_meshid, x, y, z):
    return _hrl.HRL_SetMeshLocation(_meshid, x, y, z)

def HRL_SetMeshRotation(_meshid, pitch, yaw, roll):
    return _hrl.HRL_SetMeshRotation(_meshid, pitch, yaw, roll)

def HRL_SetMeshScale(_meshid, x, y, z):
    return _hrl.HRL_SetMeshScale(_meshid, x, y, z)

def HRL_SetSpriteDrawOrder(_meshid, _draworder):
    return _hrl.HRL_SetSpriteDrawOrder(_meshid, _draworder)

def HRL_CreateLight(_sceneid, _type):
    return _hrl.HRL_CreateLight(_sceneid, _type)

def HRL_DeleteLight(_lightid):
    return _hrl.HRL_DeleteLight(_lightid)

def HRL_IsValidLight(_id):
    return _hrl.HRL_IsValidLight(_id)

def HRL_SetLightColor(_lightid, x, y, z):
    return _hrl.HRL_SetLightColor(_lightid, x, y, z)

def HRL_SetLightIntensity(_lightid, i):
    return _hrl.HRL_SetLightIntensity(_lightid, i)

def HRL_SetLightAttenuation(_lightid, a):
    return _hrl.HRL_SetLightAttenuation(_lightid, a)

def HRL_SetLightLocation(_lightid, x, y, z):
    return _hrl.HRL_SetLightLocation(_lightid, x, y, z)

def HRL_SetLightRotation(_lightid, pitch, yaw, roll):
    return _hrl.HRL_SetLightRotation(_lightid, pitch, yaw, roll)

def HRL_CreateTexture(_data, _bufferSize):
    return _hrl.HRL_CreateTexture(_data, _bufferSize)

def HRL_DeleteTexture(_textureid):
    return _hrl.HRL_DeleteTexture(_textureid)

def HRL_IsValidTexture(_id):
    return _hrl.HRL_IsValidTexture(_id)

def HRL_ReloadTexture(_textureid, _data, _bufferSize):
    return _hrl.HRL_ReloadTexture(_textureid, _data, _bufferSize)

def HRL_GetTextureSize(_textureid):
    return _hrl.HRL_GetTextureSize(_textureid)

def HRL_SetTextureMinFilter(_textureid, _filter):
    return _hrl.HRL_SetTextureMinFilter(_textureid, _filter)

def HRL_SetTextureMagFilter(_textureid, _filter):
    return _hrl.HRL_SetTextureMagFilter(_textureid, _filter)

def HRL_CreateTextureFromText(_text, _fontid, _font_size, _wrap_width, r, g, b, bg_r, bg_g, bg_b, bg_a):
    return _hrl.HRL_CreateTextureFromText(_text, _fontid, _font_size, _wrap_width, r, g, b, bg_r, bg_g, bg_b, bg_a)

def HRL_ClearScreen():
    return _hrl.HRL_ClearScreen()

def HRL_CreateScene(_renderOnScreen):
    return _hrl.HRL_CreateScene(_renderOnScreen)

def HRL_DeleteScene(_sceneid):
    return _hrl.HRL_DeleteScene(_sceneid)

def HRL_IsValidScene(_id):
    return _hrl.HRL_IsValidScene(_id)

def HRL_ResizeSceneTexture(_sceneid, _width, _height):
    return _hrl.HRL_ResizeSceneTexture(_sceneid, _width, _height)

def HRL_EnableColorPickingBuffer(_scene, _enable):
    return _hrl.HRL_EnableColorPickingBuffer(_scene, _enable)

def HRL_CreatePostProcess(_viewport, _matid, priority):
    return _hrl.HRL_CreatePostProcess(_viewport, _matid, priority)

def HRL_DeletePostProcess(_postid):
    return _hrl.HRL_DeletePostProcess(_postid)

def HRL_IsValidPostProcess(_id):
    return _hrl.HRL_IsValidPostProcess(_id)

def HRL_CreateShader(_vertData, _vertSize, _fragData, _fragSize):
    return _hrl.HRL_CreateShader(_vertData, _vertSize, _fragData, _fragSize)

def HRL_DeleteShader(_shaderid):
    return _hrl.HRL_DeleteShader(_shaderid)

def HRL_IsValidShader(_id):
    return _hrl.HRL_IsValidShader(_id)

def HRL_CreateMaterial(_shaderid):
    return _hrl.HRL_CreateMaterial(_shaderid)

def HRL_DeleteMaterial(_matid):
    return _hrl.HRL_DeleteMaterial(_matid)

def HRL_IsValidMaterial(_id):
    return _hrl.HRL_IsValidMaterial(_id)

def HRL_MaterialSetInt(_matid, _uniformName, a):
    return _hrl.HRL_MaterialSetInt(_matid, _uniformName, a)

def HRL_MaterialSetTexture(_matid, _uniformName, _textureid):
    return _hrl.HRL_MaterialSetTexture(_matid, _uniformName, _textureid)

def HRL_MaterialSetBool(_matid, _uniformName, a):
    return _hrl.HRL_MaterialSetBool(_matid, _uniformName, a)

def HRL_MaterialSetFloat(_matid, _uniformName, a):
    return _hrl.HRL_MaterialSetFloat(_matid, _uniformName, a)

def HRL_MaterialSetVec2(_matid, _uniformName, x, y):
    return _hrl.HRL_MaterialSetVec2(_matid, _uniformName, x, y)

def HRL_MaterialSetVec3(_matid, _uniformName, x, y, z):
    return _hrl.HRL_MaterialSetVec3(_matid, _uniformName, x, y, z)

def HRL_MaterialSetVec4(_matid, _uniformName, x, y, z, w):
    return _hrl.HRL_MaterialSetVec4(_matid, _uniformName, x, y, z, w)

def HRL_MaterialSetEmissiveColor(matid, r, g, b, a):
    return _hrl.HRL_MaterialSetEmissiveColor(matid, r, g, b, a)

def HRL_CreateViewport(_sceneid, _cameraid, x, y, _width, _height):
    return _hrl.HRL_CreateViewport(_sceneid, _cameraid, x, y, _width, _height)

def HRL_DeleteViewport(_viewportid):
    return _hrl.HRL_DeleteViewport(_viewportid)

def HRL_IsValidViewport(_id):
    return _hrl.HRL_IsValidViewport(_id)

def HRL_SetViewportCamera(_viewportid, _camid):
    return _hrl.HRL_SetViewportCamera(_viewportid, _camid)

def HRL_SetViewportRect(_viewportid, x, y, _width, _height):
    return _hrl.HRL_SetViewportRect(_viewportid, x, y, _width, _height)

def HRL_CreateCamera(_sceneid, _type):
    return _hrl.HRL_CreateCamera(_sceneid, _type)

def HRL_DeleteCamera(_camid):
    return _hrl.HRL_DeleteCamera(_camid)

def HRL_IsValidCamera(_id):
    return _hrl.HRL_IsValidCamera(_id)

def HRL_SetCameraType(_camid, _type):
    return _hrl.HRL_SetCameraType(_camid, _type)

def HRL_SetCameraOrthoVertical(_camid, _height):
    return _hrl.HRL_SetCameraOrthoVertical(_camid, _height)

def HRL_SetCameraPerspectiveFov(_camid, _fov):
    return _hrl.HRL_SetCameraPerspectiveFov(_camid, _fov)

def HRL_SetCameraNearPlane(_camid, _nearPlane):
    return _hrl.HRL_SetCameraNearPlane(_camid, _nearPlane)

def HRL_SetCameraFarPlane(_camid, _farPlane):
    return _hrl.HRL_SetCameraFarPlane(_camid, _farPlane)

def HRL_SetCameraLocation(_camid, x, y, z):
    return _hrl.HRL_SetCameraLocation(_camid, x, y, z)

def HRL_SetCameraRotation(_camid, pitch, yaw, roll):
    return _hrl.HRL_SetCameraRotation(_camid, pitch, yaw, roll)

def HRL_SetFogEnabled(scene, enable):
    return _hrl.HRL_SetFogEnabled(scene, enable)

def HRL_SetFogMode(scene, mode):
    return _hrl.HRL_SetFogMode(scene, mode)

def HRL_SetFogColor(scene, r, g, b):
    return _hrl.HRL_SetFogColor(scene, r, g, b)

def HRL_SetFogDensity(scene, density):
    return _hrl.HRL_SetFogDensity(scene, density)

def HRL_SetFogLinearRange(scene, start, end):
    return _hrl.HRL_SetFogLinearRange(scene, start, end)

def HRL_GetProjectionMatrix(aa):
    return _hrl.HRL_GetProjectionMatrix(aa)

def HRL_GetViewMatrix(aa):
    return _hrl.HRL_GetViewMatrix(aa)

def HRL_GetModelMatrix(_meshid, aa):
    return _hrl.HRL_GetModelMatrix(_meshid, aa)

def HRL_DrawSceneAsDebugMode(_sceneid, mode):
    return _hrl.HRL_DrawSceneAsDebugMode(_sceneid, mode)

def HRL_SetDebugLineThickness(a):
    return _hrl.HRL_SetDebugLineThickness(a)

def HRL_DrawDebugSegment(_sceneid, a_x, a_y, a_z, b_x, b_y, b_z, r, g, b):
    return _hrl.HRL_DrawDebugSegment(_sceneid, a_x, a_y, a_z, b_x, b_y, b_z, r, g, b)

def HRL_DrawDebugPolygon(_sceneid, _mode, vertices_x, vertices_y, vertices_z, vertices_count, r, g, b):
    return _hrl.HRL_DrawDebugPolygon(_sceneid, _mode, vertices_x, vertices_y, vertices_z, vertices_count, r, g, b)

def HRL_DrawDebugCircle(_sceneid, _mode, center_x, center_y, center_z, radius, segments, r, g, b):
    return _hrl.HRL_DrawDebugCircle(_sceneid, _mode, center_x, center_y, center_z, radius, segments, r, g, b)

def HRL_DrawDebugCapsule(_sceneid, _mode, a_x, a_y, a_z, b_x, b_y, b_z, radius, segments, r, g, b):
    return _hrl.HRL_DrawDebugCapsule(_sceneid, _mode, a_x, a_y, a_z, b_x, b_y, b_z, radius, segments, r, g, b)

def HRL_DrawDebugPoint(_sceneid, a_x, a_y, a_z, size, r, g, b):
    return _hrl.HRL_DrawDebugPoint(_sceneid, a_x, a_y, a_z, size, r, g, b)

def HRL_TakeScreenshot(_sceneid, _target_path):
    return _hrl.HRL_TakeScreenshot(_sceneid, _target_path)

def HRL_SetAntialiasingMode(_mode):
    return _hrl.HRL_SetAntialiasingMode(_mode)

def HRL_CreateFont(_data, _data_size):
    return _hrl.HRL_CreateFont(_data, _data_size)

def HRL_DeleteFont(_fontid):
    return _hrl.HRL_DeleteFont(_fontid)

def HRL_IsValidFont(_id):
    return _hrl.HRL_IsValidFont(_id)

def HRL_GetLastError():
    import ctypes
    lib = ctypes.cdll.LoadLibrary("libhrldll.dll")
    lib.HRL_GetLastError.restype = ctypes.c_int
    detail = ctypes.c_char_p()
    severity = ctypes.c_int()
    err = lib.HRL_GetLastError(ctypes.byref(detail), ctypes.byref(severity))
    return err, detail.value.decode() if detail.value else "", severity.value


